import os
import time
from kirosu.agent import HubClient

def main():
    HOST = "127.0.0.1"
    PORT = int(os.environ.get("KIRO_SWARM_PORT", 8765))
    client = HubClient(HOST, PORT)
    
    # Ensure demo_artifacts directory exists
    os.makedirs("demo_artifacts", exist_ok=True)
    
    print("1. Enqueuing Artifact Generation Task...")
    # We ask the agent to create a file
    prompt = """
    Create a markdown file named 'demo_artifacts/hello_kirosu.md' with the following content:
    
    # Hello Kirosu!
    This file was generated by a Kirosu agent.
    
    - Timestamp: {timestamp}
    - Agent: {agent_id}
    
    Use python to write the file.
    """.format(timestamp=time.ctime(), agent_id="kirosu-agent")
    
    resp = client.call("enqueue", {"prompt": prompt, "type": "chat"})
    task_id = resp["task_id"]
    print(f"Task ID: {task_id}")
    
    # Wait for completion
    while True:
        tasks = client.call("list", {"limit": 100})["tasks"]
        task = next((t for t in tasks if t["task_id"] == task_id), None)
        if task and task["status"] in ["done", "failed"]:
            print(f"Task Status: {task['status']}")
            print(f"Result: {task.get('result') or task.get('error')}")
            break
        time.sleep(1)
        
    # Verify artifact
    if os.path.exists("demo_artifacts/hello_kirosu.md"):
        print("\n✅ Artifact created successfully!")
        with open("demo_artifacts/hello_kirosu.md", "r") as f:
            print(f"Content:\n{f.read()}")
    else:
        print("\n❌ Artifact not found.")

if __name__ == "__main__":
    main()
